PACKAGE_NAME="hid-shanwan"
PACKAGE_VERSION="0.1"

BUILT_MODULE_NAME[0]="hid-shanwan"
BUILT_MODULE_LOCATION[0]="."

DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"

MAKE[0]="make"
CLEAN="make clean"